### ISSUE TITLE
node-forge vulnerability

### ISSUE THREAD

**Issue by sroehrl** [gaudiamus-css/gaudiamus-starter#8]
When forking this repository a security warning concerning node-forge shows up. It might be a dependency from the parcel version the package uses or require a simple patch. Either way: It's probably a simple fix

**Comment by SuchismitaDhal** [comment]
I just forked the repository without getting any warning
Can you explain how do I replicate the issue?

**Comment by sroehrl** [comment]
You did? This issue was reported to me, so let me verify. Thank you!

**Comment by sroehrl** [comment]
You are right! This issue is already resolved due to updates of HTML5 boilerplate. Thank you
